version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "80:5000"
    command: sh -c "sleep 10s ; python3 ./test.py"
    links:
      - percona-db

  percona-db:
    build: ./app
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
