version: '3.8'

services:
  app:
    build: ./app
    ports:
      - 80:5000
    restart: always
    links:
      - db
  
  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
       - ./db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080