version: '3.8'

services:
  app:
    build: ./app
    ports:
      - 80:5000
    links:
      - percona-db
    volumes:
      - percona-app:/app
  percona-db:
    image: percona/percona-server
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - percona-app:/db
  volumes:
    percona-app: 
      external: true