version: '3.8'

services:
  app:
    build: ./app
    ports:
      - 80:5000
    links:
      - db

  db:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - '3306'