version: '3.8'

services:
  app:
    build: ./app
    ports:
      - 80:5000
    links:
      - db
    command:
      ls
  
  db:
    image: percona/percona-server
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - percona-vol:/var/lib/mysql

volumes:
  percona-vol: 