version: '3.8'

services:
  app:
    build: ./app
    ports:
      - 80:5000
    links:
      - db
    volumes:
      - ./app:/app
  
  db:
    image: percona/percona-server
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

volumes:
  percona-vol: 